insert into projects(title, category, funding_goal, start_date, end_date) values ("guitar", "music", 3000, "aug 1", "aug 30");
insert into projects(title, category, funding_goal, start_date, end_date) values ("patio", "home", 5000, "aug 1", "aug 30");
insert into projects(title, category, funding_goal, start_date, end_date) values ("phone", "necessities", 2000, "aug 1", "aug 30");
insert into projects(title, category, funding_goal, start_date, end_date) values ("jimmy choo", "shoes", 1500, "aug 1", "aug 30");
insert into projects(title, category, funding_goal, start_date, end_date) values ("bike", "health", 7500, "aug 1", "aug 30");
insert into projects(title, category, funding_goal, start_date, end_date) values ("school supplies", "sadaqa", 4000, "aug 1", "aug 30");
insert into projects(title, category, funding_goal, start_date, end_date) values ("vitamix", "home", 5000, "aug 1", "aug 30");
insert into projects(title, category, funding_goal, start_date, end_date) values ("music lessons", "music", 2200, "aug 1", "aug 30");
insert into projects(title, category, funding_goal, start_date, end_date) values ("dyson", "home", 3500, "aug 1", "aug 30");
insert into projects(title, category, funding_goal, start_date, end_date) values ("speakers", "music", 10000, "aug 1", "aug 30");


insert into users(name, age) values("sara", 11);
insert into users(name, age) values("maliha", 17);
insert into users(name, age) values("mohammed", 12);
insert into users(name, age) values("ammar", 14);
insert into users(name, age) values("rayyan", 11);
insert into users(name, age) values("dina", 8);
insert into users(name, age) values("amirah", 2);
insert into users(name, age) values("alina", 4);
insert into users(name, age) values("minha", 5);
insert into users(name, age) values("miesha", 3);
insert into users(name, age) values("yusuf", 6);
insert into users(name, age) values("iliya", 3);
insert into users(name, age) values("sanaya", 3);
insert into users(name, age) values("abdullah", 13);
insert into users(name, age) values("maryam", 3);
insert into users(name, age) values("ali", 1);
insert into users(name, age) values("ibrahim", 16);
insert into users(name, age) values("asiya", 19);
insert into users(name, age) values("ayesha", 15);
insert into users(name, age) values("zahra", 9);


insert into pledges(amount, user_id, project_id) values (50, 1, 1);
insert into pledges(amount, user_id, project_id) values (500, 2, 2);
insert into pledges(amount, user_id, project_id) values (30, 3, 3);
insert into pledges(amount, user_id, project_id) values (300, 4, 2);
insert into pledges(amount, user_id, project_id) values (200, 5, 4);
insert into pledges(amount, user_id, project_id) values (250, 6, 5);
insert into pledges(amount, user_id, project_id) values (101, 7, 6);
insert into pledges(amount, user_id, project_id) values (60, 8, 6);
insert into pledges(amount, user_id, project_id) values (201, 9, 7);
insert into pledges(amount, user_id, project_id) values (45, 10, 7);
insert into pledges(amount, user_id, project_id) values (51, 1, 8);
insert into pledges(amount, user_id, project_id) values (25, 2, 8);
insert into pledges(amount, user_id, project_id) values (1001, 3, 9);
insert into pledges(amount, user_id, project_id) values (500, 4, 9);
insert into pledges(amount, user_id, project_id) values (501, 5, 10);
insert into pledges(amount, user_id, project_id) values (20, 6, 11);
insert into pledges(amount, user_id, project_id) values (200, 7, 12);
insert into pledges(amount, user_id, project_id) values (100, 8, 13);
insert into pledges(amount, user_id, project_id) values (50, 9, 15);
insert into pledges(amount, user_id, project_id) values (30, 10, 16);
insert into pledges(amount, user_id, project_id) values (500, 1, 14);
insert into pledges(amount, user_id, project_id) values (50, 2, 17);
insert into pledges(amount, user_id, project_id) values (20, 3, 8);
insert into pledges(amount, user_id, project_id) values (35, 4, 19);
insert into pledges(amount, user_id, project_id) values (100, 5, 18);
insert into pledges(amount, user_id, project_id) values (200, 6, 20);
insert into pledges(amount, user_id, project_id) values (30, 7, 20);
insert into pledges(amount, user_id, project_id) values (400, 8, 15);
insert into pledges(amount, user_id, project_id) values (150, 9, 16);
insert into pledges(amount, user_id, project_id) values (30, 10, 9);
